#!/usr/bin/env python3
"""
Provably-fair local lottery on BTCPay Server + Lightning preimages.
Version 2: English, Noderunners-style UI, security hardening.

HOW IT WORKS
------------
1. Buyers pick a number of tickets on the page; the app creates a BTCPay
   invoice (amount = count × price) and sends them to checkout. After paying,
   BTCPay redirects back to PUBLIC_URL/?invoice=<invoice id> and the page shows their
   ticket numbers. POS sales work too: the app also polls BTCPay for any
   settled invoices between START_TIME and END_TIME.
   Ticket count is derived from the AMOUNT PAID (never from client-editable
   metadata). Each invoice yields a Lightning preimage as proof of payment.
2. Every invoice gets a random 7-character ticket ID (A-Z, a-z, 0-9) generated by
   this app, unique within the state file, plus a 5-digit verification code.
   "<ticket id>-<code>" (e.g. "Kq7zR2x-48213") is set as the BTCPay orderId and
   as the invoice memo (itemDesc), so the buyer sees both in their wallet.
   Public ticket numbers: "Kq7zR2x", or "Kq7zR2x-1", "Kq7zR2x-2"… for several
   tickets on one invoice. Only the SHA-256 of the code is stored.
   POS sales without an orderId get an ID assigned when they are picked up
   and have no verification code.
3. When END_TIME passes, the ticket list is frozen and a commitment hash of
   the frozen list is published BEFORE the drawing block is known.
4. The first Bitcoin block with a timestamp >= END_TIME decides the draw.
   For prize n: SHA256(blockhash + frozen list + n) mod remaining tickets.
   The winning ticket leaves the pool; the buyer's other tickets stay in.
   PRIZE_COUNT sets how many prizes are drawn from that one block.
   BACKUP_COUNT more rounds draw stand-in tickets (same formula, rounds
   PRIZE_COUNT+1…). If a winner has left, the organizer forfeits that prize
   and it goes to the next unused backup, in draw order.
5. The winning ticket number is published. The verification code and the
   preimage are never published. At the counter the organizer:
     a) VERIFIES: types the verification code the winner shows from their
        wallet memo (or the Lightning preimage, when the funding source
        provides one); the server answers match / no match, or
     b) REVEALS: with the admin token, shows the stored preimage if there is
        one (fallback, only on a screen the public can't see).

CONFIGURATION IS VIA ENVIRONMENT VARIABLES — see the CONFIG section.
Run with a real WSGI server behind HTTPS (see bottom of file).

CHECK BEFORE GOING LIVE
-----------------------
- Confirm where your BTCPay version puts the Lightning preimage in the
  payment-methods response (fetch_invoice_preimage) — test with curl first.
- Confirm BTCPay's public receipt page for an invoice does NOT expose the
  preimage. Raw invoice IDs are never shown on the public page.
- Set TICKET_PRICE_SATS to the exact ticket price used in your POS.
"""

import hashlib
import hmac
import json
import os
import secrets
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
from collections import defaultdict
from datetime import datetime

from flask import Flask, abort, jsonify, render_template_string, request, send_file
from werkzeug.middleware.proxy_fix import ProxyFix

# ---------------------------------------------------------------------------
# CONFIG — set via environment variables (never hardcode secrets in the file)
# ---------------------------------------------------------------------------

BTCPAY_URL = os.environ.get("BTCPAY_URL", "https://your-btcpay.example").rstrip("/")
BTCPAY_API_KEY = os.environ.get("BTCPAY_API_KEY", "")
BTCPAY_STORE_ID = os.environ.get("BTCPAY_STORE_ID", "")

START_TIME = os.environ.get("LOTTERY_START", "2026-09-13T10:00:00+02:00")
END_TIME = os.environ.get("LOTTERY_END", "2026-09-13T17:00:00+02:00")

# Public URL of this lottery page; BTCPay redirects buyers back here after paying.
PUBLIC_URL = os.environ.get("PUBLIC_URL", "http://127.0.0.1:8000").rstrip("/")

TICKET_PRICE_SATS = int(os.environ.get("TICKET_PRICE_SATS", "2100"))
MAX_TICKETS_PER_INVOICE = int(os.environ.get("MAX_TICKETS_PER_INVOICE", "50"))

# Number of prizes drawn from the same block. Prize 1 is drawn first.
# Each winning ticket is removed from the pool; the buyer's other tickets stay in.
PRIZE_COUNT = int(os.environ.get("PRIZE_COUNT", "1"))
# Extra tickets drawn after the prizes, in order, as stand-ins for winners who
# already left. Same block, same formula (rounds PRIZE_COUNT+1 …).
BACKUP_COUNT = int(os.environ.get("BACKUP_COUNT", "2"))
# Optional labels, "|" separated, e.g. "Hardware wallet|T-shirt|Sticker pack"
PRIZE_LABELS = [x.strip() for x in os.environ.get("PRIZE_LABELS", "").split("|") if x.strip()]

# Shown in the page header and title.
LOTTERY_NAME = os.environ.get("LOTTERY_NAME", "Noderunners")
LOTTERY_SUBTITLE = os.environ.get("LOTTERY_SUBTITLE", "Lightning lottery")
# Logo shown top-left. Put the file in ./data (bind-mounted to /data) and name it here.
LOGO_FILE = os.environ.get("LOGO_FILE", "/data/logo.png")
# Portrait photo of the main prize, shown at the top of the "Buy tickets" card.
PRIZE_IMAGE_FILE = os.environ.get("PRIZE_IMAGE_FILE", "/data/prize.png")

ADMIN_TOKEN = os.environ.get("ADMIN_TOKEN", "")

# Ticket IDs: 7 characters from this alphabet (case-sensitive), generated here, unique per event.
TICKET_ID_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
TICKET_ID_LENGTH = 7
# Verification code: 5 digits, sent with the ticket ID as orderId/memo ("Kq7zR2x-48213").
# The winner shows it at the counter; only its SHA-256 is stored here.
VERIFICATION_CODE_LENGTH = 5

# Cloudflare (and similar) block Python's default urllib User-Agent (error 1010).
USER_AGENT = "btcpay-lottery/1.0"

POLL_INTERVAL_INVOICES = 15
POLL_INTERVAL_BLOCKS = 20
BLOCK_API = os.environ.get("BLOCK_API", "https://mempool.space/api")

DATA_FILE = os.environ.get("DATA_FILE", "lottery_data.json")

# Behind a reverse proxy (Caddy/nginx) the client IP arrives in X-Forwarded-For.
# TRUST_PROXY=1 means exactly one trusted proxy in front; without it every
# visitor would share the proxy's IP and therefore one rate-limit bucket.
TRUST_PROXY = int(os.environ.get("TRUST_PROXY", "0"))

if not ADMIN_TOKEN:
    raise SystemExit("Set ADMIN_TOKEN (e.g. `python3 -c 'import secrets;print(secrets.token_hex(32))'`).")
if PRIZE_COUNT < 1:
    raise SystemExit("PRIZE_COUNT must be at least 1.")
if BACKUP_COUNT < 0:
    raise SystemExit("BACKUP_COUNT must be 0 or more.")

# ---------------------------------------------------------------------------
# STATE + PERSISTENCE
# ---------------------------------------------------------------------------

_lock = threading.Lock()


def _load():
    if os.path.exists(DATA_FILE):
        with open(DATA_FILE) as f:
            return json.load(f)
    return {"phase": "sales", "invoices": {}, "pending": {}, "commitment": None, "winner": None}


def _save(state):
    tmp = DATA_FILE + ".tmp"
    with open(tmp, "w") as f:
        json.dump(state, f, indent=2)
    os.replace(tmp, DATA_FILE)  # atomic write


STATE = _load()

# ---------------------------------------------------------------------------
# HELPERS
# ---------------------------------------------------------------------------


def parse_iso(s: str) -> float:
    return datetime.fromisoformat(s).timestamp()


START_UNIX = parse_iso(START_TIME)
END_UNIX = parse_iso(END_TIME)


def _used_ticket_ids(state) -> set:
    """Every base ticket ID in the state file: settled invoices and unpaid pending ones."""
    used = {inv["ticket_id"] for inv in state["invoices"].values() if inv.get("ticket_id")}
    used.update(state.get("pending", {}).keys())
    return used


def new_ticket_id(state) -> str:
    """Random 7-char ID (A-Z, a-z, 0-9); regenerated until it is not already in the state.
    Caller must hold _lock."""
    used = _used_ticket_ids(state)
    while True:
        tid = "".join(secrets.choice(TICKET_ID_ALPHABET) for _ in range(TICKET_ID_LENGTH))
        if tid not in used:
            return tid


def is_valid_ticket_id(tid) -> bool:
    return (isinstance(tid, str) and len(tid) == TICKET_ID_LENGTH
            and all(c in TICKET_ID_ALPHABET for c in tid))


def new_verification_code() -> str:
    return "".join(secrets.choice("0123456789") for _ in range(VERIFICATION_CODE_LENGTH))


def is_valid_verification_code(code) -> bool:
    return isinstance(code, str) and len(code) == VERIFICATION_CODE_LENGTH and code.isdigit()


def order_id_for(ticket_id: str, code: str) -> str:
    return f"{ticket_id}-{code}"


def split_order_id(order_id) -> tuple:
    """"Kq7zR2x-48213" -> ("Kq7zR2x", "48213"); "Kq7zR2x" -> ("Kq7zR2x", None); junk -> (None, None)."""
    if not isinstance(order_id, str):
        return None, None
    tid, _, code = order_id.strip().partition("-")
    if not is_valid_ticket_id(tid):
        return None, None
    return tid, (code if is_valid_verification_code(code) else None)


def _sha256(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def ticket_ids_for(ticket_id: str, count: int) -> list:
    """One ticket keeps the bare ID; several tickets on one invoice get -1, -2, …"""
    if count == 1:
        return [ticket_id]
    return [f"{ticket_id}-{i + 1}" for i in range(count)]


def all_ticket_ids(state) -> list:
    out = []
    for inv in state["invoices"].values():
        out.extend(inv["ticket_ids"])
    return sorted(out)


# ---------------------------------------------------------------------------
# BTCPAY GREENFIELD API
# ---------------------------------------------------------------------------


def _btcpay_get(path: str, params: dict = None):
    url = f"{BTCPAY_URL}{path}"
    if params:
        url += "?" + urllib.parse.urlencode(params, doseq=True)
    req = urllib.request.Request(url, headers={"Authorization": f"token {BTCPAY_API_KEY}", "User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read().decode())


def _btcpay_post(path: str, body: dict):
    req = urllib.request.Request(
        f"{BTCPAY_URL}{path}",
        data=json.dumps(body).encode(),
        headers={"Authorization": f"token {BTCPAY_API_KEY}", "Content-Type": "application/json", "User-Agent": USER_AGENT},
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=15) as r:
        return json.loads(r.read().decode())


def create_ticket_invoice(count: int, order_id: str) -> dict:
    """Create a BTCPay invoice for `count` tickets. Returns {"id", "checkoutLink"}.
    order_id = "<ticket id>-<verification code>", sent as orderId and as the memo (itemDesc).
    API key needs the btcpay.store.cancreateinvoice permission."""
    body = {
        "amount": str(count * TICKET_PRICE_SATS),
        "currency": "SATS",
        "metadata": {"orderId": order_id, "itemDesc": order_id, "ticketCount": count},
        "checkout": {
            # {InvoiceId}, not {OrderId}: the orderId carries the verification code and
            # the redirect URL ends up in BTCPay/browser/proxy logs.
            "redirectURL": f"{PUBLIC_URL}/?invoice={{InvoiceId}}",
            "redirectAutomatically": True,
        },
    }
    inv = _btcpay_post(f"/api/v1/stores/{BTCPAY_STORE_ID}/invoices", body)
    return {"id": inv["id"], "checkoutLink": inv["checkoutLink"]}


def fetch_invoice(invoice_id: str) -> dict:
    return _btcpay_get(f"/api/v1/stores/{BTCPAY_STORE_ID}/invoices/{invoice_id}")


def fetch_settled_invoices_in_window():
    """All Settled invoices created in [START, END], with pagination."""
    out, skip, take = [], 0, 100
    while True:
        page = _btcpay_get(
            f"/api/v1/stores/{BTCPAY_STORE_ID}/invoices",
            {
                "startDate": int(START_UNIX),
                "endDate": int(END_UNIX),
                "status": ["Settled"],
                "skip": skip,
                "take": take,
            },
        )
        out.extend(page)
        if len(page) < take:
            return out
        skip += take


def fetch_invoice_preimage(invoice_id: str):
    """
    Locate the Lightning preimage in the payment-methods response.
    Field names vary by BTCPay version — verify with:
      curl -H "Authorization: token $KEY" \
        $BTCPAY_URL/api/v1/stores/$STORE/invoices/$ID/payment-methods
    """
    methods = _btcpay_get(f"/api/v1/stores/{BTCPAY_STORE_ID}/invoices/{invoice_id}/payment-methods")
    for m in methods:
        pm = (m.get("paymentMethodId") or m.get("paymentMethod") or "").lower()
        if "ln" not in pm and "lightning" not in pm:
            continue
        # BTCPay 2.x: preimage lives in additionalData on the payment method
        extra = m.get("additionalData") or {}
        if isinstance(extra, dict) and extra.get("preimage"):
            return extra["preimage"]
        # Older versions: inside each payment entry
        for p in m.get("payments", []):
            for key in ("preimage", "paymentProof"):
                v = p.get(key)
                if v:
                    return v
            details = p.get("details") or {}
            if isinstance(details, dict):
                for key in ("preimage", "paymentProof"):
                    if details.get(key):
                        return details[key]
    return None


def ticket_count_from_invoice(inv: dict) -> int:
    """Derive ticket count from amount paid, in sats. Never trust metadata."""
    amount = float(inv.get("amount", 0))
    currency = (inv.get("currency") or "").upper()
    if currency == "SATS":
        sats = amount
    elif currency == "BTC":
        sats = amount * 100_000_000
    else:
        # Fiat-priced tickets: convert via your own fixed rule, or price in SATS.
        # Refusing here is safer than guessing.
        return 0
    count = int(sats // TICKET_PRICE_SATS)
    return max(0, min(count, MAX_TICKETS_PER_INVOICE))


def _resolve_ticket_id(state, inv: dict) -> tuple:
    """(ticket id, verification code) from the orderId this app put on the invoice.
    POS sales (no orderId) or a collision with an already settled invoice get a
    fresh ticket ID and no verification code. Caller must hold _lock."""
    inv_id = inv["id"]
    tid, code = split_order_id((inv.get("metadata") or {}).get("orderId"))
    pending = state.setdefault("pending", {})
    if tid:
        taken = any(o.get("ticket_id") == tid for o in state["invoices"].values())
        reserved_for_other = tid in pending and pending[tid] != inv_id
        if not taken and not reserved_for_other:
            pending.pop(tid, None)
            return tid, code
        print(f"[sync] ticket id {tid} on invoice {inv_id} already used, regenerating")
    return new_ticket_id(state), None


def ingest_invoice(inv: dict) -> bool:
    """Register a settled invoice as tickets. Returns True if (now) registered."""
    inv_id = inv["id"]
    with _lock:
        if inv_id in STATE["invoices"]:
            return True
        if STATE["phase"] != "sales":
            return False
    if inv.get("status") not in ("Settled",):
        return False
    created = inv.get("createdTime")
    if created is not None and not (START_UNIX <= float(created) <= END_UNIX):
        return False
    try:
        preimage = fetch_invoice_preimage(inv_id)
    except Exception as e:
        print(f"[sync] preimage lookup failed for {inv_id}: {e}")
        return False
    if not preimage:
        # BTCPay sometimes reports a settled Lightning payment with preimage null.
        # The buyer paid, so register the tickets; the preimage is retried each poll.
        print(f"[sync] {inv_id}: settled but BTCPay returned no preimage (yet), registering anyway")
    count = ticket_count_from_invoice(inv)
    if count == 0:
        print(f"[sync] {inv_id} paid below ticket price / unknown currency, skipped")
        return False
    with _lock:
        if STATE["phase"] != "sales":
            return False
        tid, code = _resolve_ticket_id(STATE, inv)
        STATE["invoices"][inv_id] = {
            "ticket_id": tid,
            "ticket_ids": ticket_ids_for(tid, count),
            "verification_sha256": _sha256(code) if code else None,
            "preimage_sha256": _sha256(preimage) if preimage else None,
            "preimage": preimage,
            "created": created,
        }
        _save(STATE)
        print(f"[sync] {inv_id}: {count} ticket(s)")
    return True


def sync_invoices():
    try:
        invoices = fetch_settled_invoices_in_window()
    except Exception as e:  # network / auth / JSON errors
        print(f"[sync] failed: {e}")
        return
    for inv in invoices:
        ingest_invoice(inv)
    retry_missing_preimages()


def retry_missing_preimages():
    """Fill in preimages for registered invoices where BTCPay had none at ingest time."""
    with _lock:
        missing = [i for i, o in STATE["invoices"].items() if not o.get("preimage")]
    for inv_id in missing:
        try:
            preimage = fetch_invoice_preimage(inv_id)
        except Exception as e:
            print(f"[sync] preimage retry failed for {inv_id}: {e}")
            continue
        if not preimage:
            continue
        with _lock:
            STATE["invoices"][inv_id]["preimage"] = preimage
            STATE["invoices"][inv_id]["preimage_sha256"] = hashlib.sha256(preimage.encode()).hexdigest()
            _save(STATE)
        print(f"[sync] {inv_id}: preimage arrived")


# ---------------------------------------------------------------------------
# BLOCKCHAIN
# ---------------------------------------------------------------------------


def _get(url: str):
    req = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    with urllib.request.urlopen(req, timeout=15) as r:
        return r.read().decode().strip()


def tip_height() -> int:
    return int(_get(f"{BLOCK_API}/blocks/tip/height"))


def block_info(height: int) -> dict:
    h = _get(f"{BLOCK_API}/block-height/{height}")
    info = json.loads(_get(f"{BLOCK_API}/block/{h}"))
    return {"height": height, "hash": h, "timestamp": info["timestamp"]}


def wait_for_drawing_block(end_unix: int) -> dict:
    """First block whose timestamp >= end_unix. Retries on network errors."""
    seen = None
    while True:
        try:
            h = tip_height()
            if h != seen:
                seen = h
                info = block_info(h)
                if info["timestamp"] >= end_unix:
                    return info
        except Exception as e:
            print(f"[block] poll error: {e}")
        time.sleep(POLL_INTERVAL_BLOCKS)


# ---------------------------------------------------------------------------
# DRAW
# ---------------------------------------------------------------------------


def commitment_of(tickets: list) -> str:
    return hashlib.sha256(",".join(tickets).encode()).hexdigest()


def draw(tickets: list, block_hash: str, prize_count: int = 1, backup_count: int = 0) -> list:
    """
    Draw up to `prize_count` winners plus `backup_count` stand-ins from one block.
    Round n:  SHA256(blockhash + "," + <frozen sorted list> + "," + n)  mod  <remaining tickets>
    The winning ticket is removed from the pool before the next round; other
    tickets of the same buyer stay in. The frozen list in the hash input never
    changes, so anyone can replay every round with just the block hash.
    Rounds 1..prize_count are prizes; rounds after that are backups, in order.
    """
    frozen = sorted(tickets)
    pool = list(frozen)
    results = []
    for n in range(1, min(prize_count + backup_count, len(frozen)) + 1):
        hash_input = block_hash + "," + ",".join(frozen) + "," + str(n)
        digest = hashlib.sha256(hash_input.encode()).hexdigest()
        idx = int(digest, 16) % len(pool)
        ticket = pool.pop(idx)
        entry = {
            "prize": n,
            "label": PRIZE_LABELS[n - 1] if n - 1 < len(PRIZE_LABELS) else f"Prize {n}",
            "hash_input": hash_input,
            "sha256": digest,
            "index": idx,
            "pool_size": len(pool) + 1,
            "ticket": ticket,
            "claimed": False,
        }
        if n > prize_count:
            entry["backup"] = n - prize_count
            entry["label"] = f"Backup {n - prize_count}"
            entry["used_for"] = None
        results.append(entry)
    return results


def forfeit_prize(state, prize_no: int):
    """Winner didn't show: hand prize `prize_no` to the next unused backup ticket.
    Returns (prize entry, error message). Caller must hold _lock."""
    w = state.get("winner")
    if not w:
        return None, "no winner yet"
    prize = next((p for p in w["prizes"] if p["prize"] == prize_no), None)
    if prize is None:
        return None, "unknown prize"
    if prize.get("claimed"):
        return None, "this prize was already claimed"
    backup = next((b for b in w.get("backups", []) if b.get("used_for") is None), None)
    if backup is None:
        return None, "no backup tickets left"
    prize.setdefault("forfeited", []).append(prize["ticket"])
    prize["ticket"] = backup["ticket"]
    prize["from_backup"] = backup["backup"]
    backup["used_for"] = prize_no
    return prize, None


def invoice_for_ticket(state, ticket_id: str):
    for inv_id, inv in state["invoices"].items():
        if ticket_id in inv["ticket_ids"]:
            return inv_id
    return None


def background_loop():
    with _lock:
        phase = STATE["phase"]
    if phase in ("winner", "no_entries"):
        # Draw already done (container restart): never redraw, it would wipe claims/forfeits.
        print(f"[draw] state file already in phase '{phase}', nothing to do")
        return
    if phase == "drawing" and STATE.get("commitment"):
        # Restarted while waiting for the block: keep the frozen list, just finish the draw.
        print("[draw] resuming: list already frozen, waiting for the drawing block")
        _finish_draw(all_ticket_ids(STATE))
        return
    while time.time() < END_UNIX:
        if time.time() >= START_UNIX:
            sync_invoices()
        time.sleep(POLL_INTERVAL_INVOICES)

    sync_invoices()  # final sweep for invoices created before END_TIME
    with _lock:
        tickets = all_ticket_ids(STATE)
        STATE["phase"] = "drawing"
        STATE["commitment"] = {
            "ticket_count": len(tickets),
            "prize_count": PRIZE_COUNT,
            "backup_count": BACKUP_COUNT,
            "sha256_of_ticket_list": commitment_of(tickets),
            "rule": "first Bitcoin block with timestamp >= END_TIME; round n = "
                    "SHA256(blockhash,list,n) mod remaining tickets, drawn ticket removed; "
                    f"rounds 1-{PRIZE_COUNT} are prizes, later rounds are backups in order",
            "end_time": END_TIME,
        }
        _save(STATE)
    print(f"[draw] sales closed, {len(tickets)} tickets frozen, commitment published")

    _finish_draw(tickets)


def _finish_draw(tickets: list):
    if not tickets:
        with _lock:
            STATE["phase"] = "no_entries"
            _save(STATE)
        return

    blk = wait_for_drawing_block(int(END_UNIX))
    drawn = draw(tickets, blk["hash"], PRIZE_COUNT, BACKUP_COUNT)
    winners = [d for d in drawn if "backup" not in d]
    backups = [d for d in drawn if "backup" in d]
    with _lock:
        STATE["winner"] = {
            "block_height": blk["height"],
            "block_hash": blk["hash"],
            "block_timestamp": blk["timestamp"],
            "ticket_list": tickets,
            "prizes": winners,
            "backups": backups,
        }
        STATE["phase"] = "winner"
        _save(STATE)
    for w in drawn:
        print(f"[draw] {w['label']}: {w['ticket']} (block {blk['height']})")


# ---------------------------------------------------------------------------
# WEB
# ---------------------------------------------------------------------------

app = Flask(__name__)
if TRUST_PROXY:
    app.wsgi_app = ProxyFix(app.wsgi_app, x_for=TRUST_PROXY, x_proto=TRUST_PROXY, x_host=TRUST_PROXY)

# Very small in-memory rate limiter for admin endpoints: 10 attempts / 10 min / IP
_attempts = defaultdict(list)


def _rate_limited(ip: str, limit=10, window=600) -> bool:
    """Per endpoint + client IP, so a buyer's lookups don't eat the organizer's verify budget."""
    key = f"{request.endpoint}:{ip}"
    now = time.time()
    _attempts[key] = [t for t in _attempts[key] if now - t < window]
    if len(_attempts[key]) >= limit:
        return True
    _attempts[key].append(now)
    return False


def _prize_from(payload: dict):
    """Look up the prize entry (default: prize 1) from the stored draw."""
    try:
        n = int(payload.get("prize", 1))
    except (TypeError, ValueError):
        return None
    with _lock:
        w = STATE["winner"]
        if not w:
            return None
        for p in w["prizes"]:
            if p["prize"] == n:
                return dict(p)
    return None


def _admin_ok(payload: dict) -> bool:
    token = str(payload.get("token", ""))
    return hmac.compare_digest(token.encode(), ADMIN_TOKEN.encode())


@app.after_request
def security_headers(resp):
    resp.headers["Content-Security-Policy"] = (
        "default-src 'none'; script-src 'unsafe-inline'; style-src 'unsafe-inline' "
        "https://fonts.googleapis.com; font-src https://fonts.gstatic.com; img-src 'self'; connect-src 'self'"
    )
    resp.headers["X-Content-Type-Options"] = "nosniff"
    resp.headers["X-Frame-Options"] = "DENY"
    resp.headers["Referrer-Policy"] = "no-referrer"
    resp.headers["Cache-Control"] = "no-store"
    return resp


@app.route("/")
def index():
    return render_template_string(PAGE, name=LOTTERY_NAME, subtitle=LOTTERY_SUBTITLE,
                                  has_logo=os.path.isfile(LOGO_FILE),
                                  has_prize_image=os.path.isfile(PRIZE_IMAGE_FILE),
                                  main_prize=(PRIZE_LABELS[0] if PRIZE_LABELS else ""),
                                  prizes=[(i + 1, PRIZE_LABELS[i] if i < len(PRIZE_LABELS) else "")
                                          for i in range(PRIZE_COUNT)])


@app.route("/api/status")
def api_status():
    with _lock:
        w = STATE["winner"]
        public_winner = None
        if w:
            # backups stay private until one is used (then it shows up as the prize's ticket)
            public_winner = {k: v for k, v in w.items() if k != "backups"}
        return jsonify(
            {
                "phase": STATE["phase"],
                "start_time": START_TIME,
                "end_time": END_TIME,
                "ticket_price_sats": TICKET_PRICE_SATS,
                "max_per_invoice": MAX_TICKETS_PER_INVOICE,
                "prize_count": PRIZE_COUNT,
                "prize_labels": PRIZE_LABELS,
                "sales_open": STATE["phase"] == "sales" and START_UNIX <= time.time() < END_UNIX,
                "tickets": all_ticket_ids(STATE),
                "commitment": STATE["commitment"],
                "winner": public_winner,
            }
        )


def _serve_image(path: str):
    if not os.path.isfile(path):
        abort(404)
    return send_file(path, max_age=3600)


@app.route("/logo")
def logo():
    return _serve_image(LOGO_FILE)


@app.route("/prize-image")
def prize_image():
    return _serve_image(PRIZE_IMAGE_FILE)


@app.route("/api/buy", methods=["POST"])
def api_buy():
    """Create a BTCPay invoice for N tickets and return the checkout link."""
    if _rate_limited(request.remote_addr, limit=20, window=300):
        return jsonify({"error": "too many requests, slow down"}), 429
    now = time.time()
    with _lock:
        open_for_sales = STATE["phase"] == "sales"
    if not open_for_sales or not (START_UNIX <= now < END_UNIX):
        return jsonify({"error": "ticket sales are closed"}), 400
    try:
        count = int((request.get_json(silent=True) or {}).get("count", 0))
    except (TypeError, ValueError):
        count = 0
    if not (1 <= count <= MAX_TICKETS_PER_INVOICE):
        return jsonify({"error": f"choose between 1 and {MAX_TICKETS_PER_INVOICE} tickets"}), 400
    with _lock:
        tid = new_ticket_id(STATE)
        STATE.setdefault("pending", {})[tid] = None  # reserve before the invoice exists
        _save(STATE)
    order_id = order_id_for(tid, new_verification_code())
    try:
        inv = create_ticket_invoice(count, order_id)
    except Exception as e:
        print(f"[buy] invoice creation failed: {e}")
        with _lock:
            STATE["pending"].pop(tid, None)
            _save(STATE)
        return jsonify({"error": "could not create invoice, try again"}), 502
    with _lock:
        STATE["pending"][tid] = inv["id"]
        _save(STATE)
    return jsonify({**inv, "ticket_id": tid})


@app.route("/api/my-tickets")
def api_my_tickets():
    """After redirect (?invoice=<BTCPay id>): check, and if needed fetch right away, the buyer's invoice."""
    if _rate_limited(request.remote_addr, limit=60, window=300):
        return jsonify({"error": "too many requests"}), 429
    inv_id = request.args.get("invoice", "").strip()
    if not inv_id or len(inv_id) > 64 or not inv_id.isalnum():
        return jsonify({"error": "invalid invoice"}), 400
    with _lock:
        known = STATE["invoices"].get(inv_id)
    if known:
        return jsonify({"status": "settled", "tickets": known["ticket_ids"]})
    try:
        inv = fetch_invoice(inv_id)
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return jsonify({"error": "unknown invoice"}), 404
        return jsonify({"status": "pending"})
    except Exception:
        return jsonify({"status": "pending"})
    if ingest_invoice(inv):
        with _lock:
            return jsonify({"status": "settled", "tickets": STATE["invoices"][inv_id]["ticket_ids"]})
    return jsonify({"status": inv.get("status", "pending").lower()})


@app.route("/api/lookup", methods=["POST"])
def api_lookup():
    """Buyer enters the ticket ID from their wallet memo to see their ticket numbers."""
    if _rate_limited(request.remote_addr, limit=30):
        return jsonify({"error": "too many requests"}), 429
    tid, _ = split_order_id(str((request.get_json(silent=True) or {}).get("ticket_id", "")))
    if not tid:
        return jsonify({"error": "a ticket ID is 7 letters/digits (case matters)"}), 400
    with _lock:
        inv = next((o for o in STATE["invoices"].values() if o.get("ticket_id") == tid), None)
    if not inv:
        return jsonify({"error": "no paid tickets found for that ID"}), 404
    return jsonify({"tickets": inv["ticket_ids"]})


@app.route("/api/verify", methods=["POST"])
def api_verify():
    """Organizer types the verification code (or preimage) shown by the winner;
    server answers match / no match. Both are compared by SHA-256, constant time."""
    if _rate_limited(request.remote_addr):
        return jsonify({"error": "too many attempts, wait 10 minutes"}), 429
    payload = request.get_json(silent=True) or {}
    if not _admin_ok(payload):
        return jsonify({"error": "invalid token"}), 403
    claimed = str(payload.get("code", payload.get("preimage", ""))).strip()
    prize = _prize_from(payload)
    if prize is None:
        return jsonify({"error": "no winner yet / unknown prize"}), 400
    with _lock:
        inv_id = invoice_for_ticket(STATE, prize["ticket"])
        rec = STATE["invoices"][inv_id]
        stored = [h for h in (rec.get("verification_sha256"), rec.get("preimage_sha256")) if h]
    if not stored:
        return jsonify({"error": "no verification code or preimage on record for this ticket "
                                 "(POS sale?); check the invoice in BTCPay by hand"}), 409
    candidates = {claimed, claimed.lower()}
    ok = any(hmac.compare_digest(_sha256(c), h) for c in candidates for h in stored)
    if ok:
        with _lock:
            for p in STATE["winner"]["prizes"]:
                if p["prize"] == prize["prize"]:
                    p["claimed"] = True
            _save(STATE)
        print(f"[claim] prize {prize['prize']} claimed by ticket {prize['ticket']}")
    else:
        print(f"[claim] prize {prize['prize']}: verification failed")
    return jsonify({"match": ok, "prize": prize["prize"]})


@app.route("/api/reveal", methods=["POST"])
def api_reveal():
    """Fallback: show stored preimage. Only use on a screen the public can't see."""
    if _rate_limited(request.remote_addr):
        return jsonify({"error": "too many attempts, wait 10 minutes"}), 429
    payload = request.get_json(silent=True) or {}
    if not _admin_ok(payload):
        return jsonify({"error": "invalid token"}), 403
    prize = _prize_from(payload)
    if prize is None:
        return jsonify({"error": "no winner yet / unknown prize"}), 400
    with _lock:
        inv_id = invoice_for_ticket(STATE, prize["ticket"])
        preimage = STATE["invoices"][inv_id]["preimage"]
    if not preimage:
        return jsonify({"error": "BTCPay has no preimage on record for this ticket",
                        "invoice_id": inv_id}), 409
    return jsonify({"prize": prize["prize"], "preimage": preimage})


@app.route("/organizer")
def organizer():
    return render_template_string(ORGANIZER_PAGE, name=LOTTERY_NAME, subtitle=LOTTERY_SUBTITLE)


@app.route("/api/admin/state", methods=["POST"])
def api_admin_state():
    """Organizer view: phase, prizes (with history) and the private backup list."""
    if _rate_limited(request.remote_addr, limit=300, window=300):
        return jsonify({"error": "too many requests"}), 429
    if not _admin_ok(request.get_json(silent=True) or {}):
        return jsonify({"error": "invalid token"}), 403
    with _lock:
        w = STATE["winner"] or {}
        return jsonify({
            "phase": STATE["phase"],
            "ticket_count": len(all_ticket_ids(STATE)),
            "block_height": w.get("block_height"),
            "prizes": w.get("prizes", []),
            "backups": w.get("backups", []),
        })


@app.route("/api/forfeit", methods=["POST"])
def api_forfeit():
    """Winner didn't show up: give the prize to the next backup ticket (admin)."""
    if _rate_limited(request.remote_addr):
        return jsonify({"error": "too many attempts, wait 10 minutes"}), 429
    payload = request.get_json(silent=True) or {}
    if not _admin_ok(payload):
        return jsonify({"error": "invalid token"}), 403
    try:
        n = int(payload.get("prize", 1))
    except (TypeError, ValueError):
        return jsonify({"error": "unknown prize"}), 400
    with _lock:
        prize, err = forfeit_prize(STATE, n)
        if err:
            return jsonify({"error": err}), 409
        _save(STATE)
        print(f"[claim] prize {n} forfeited, now ticket {prize['ticket']} (backup {prize['from_backup']})")
        return jsonify({"prize": n, "ticket": prize["ticket"], "from_backup": prize["from_backup"]})


HEAD = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ name }} — {{ subtitle }}</title>
<link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;700;900&display=swap" rel="stylesheet">
<style>
  :root{
    --bg:#050505; --panel:#111; --line:#242424;
    --txt:#c8c8c8; --muted:#777;
    --orange:#fd6d00; --orange-2:#f37021; --green:#45ff2a;
  }
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--txt);
       font-family:'Source Sans Pro',Helvetica,Arial,sans-serif;font-size:17px;line-height:1.5}
  a{color:var(--orange)}
  header{border-bottom:3px solid var(--orange);padding:16px 20px;min-height:24px}
  header .logo{display:block;height:56px;max-width:60%;object-fit:contain;object-position:left}
  .subtitle{font-size:18px;font-weight:300;color:var(--muted);margin:0 0 14px}
  main{max-width:720px;margin:0 auto;padding:28px 20px 60px}
  h1{font-size:44px;line-height:1;font-weight:900;text-transform:uppercase;color:#fff;margin:0 0 6px}
  .phase{display:inline-block;padding:4px 12px;border:1px solid var(--line);border-radius:999px;
         text-transform:uppercase;letter-spacing:.08em;font-size:12px;font-weight:700;color:var(--muted)}
  .phase.live{border-color:var(--green);color:var(--green)}
  .phase.done{border-color:var(--orange);color:var(--orange)}
  .panel{background:var(--panel);border:1px solid var(--line);padding:20px;margin-top:22px}
  .panel h2{margin:0 0 10px;font-size:14px;text-transform:uppercase;letter-spacing:.08em;color:var(--orange)}
  .prize-photo{margin:0 0 18px;text-align:center}
  .prize-photo img{display:block;margin:0 auto;max-width:100%;max-height:420px;width:auto;border:1px solid var(--line)}
  .prize-list{list-style:none;margin:0 0 18px;padding:0;font-size:15px;line-height:1.6;color:var(--muted)}
  .prize-list li:first-child{color:#fff;font-weight:700}
  .big{font-size:64px;font-weight:900;line-height:1;color:#fff;font-variant-numeric:tabular-nums}
  .sub{color:var(--muted);font-size:14px;margin-top:4px}
  .tickets{columns:3;column-gap:16px;font-family:monospace;font-size:14px;margin-top:14px;color:#9a9a9a}
  @media (max-width:520px){.tickets{columns:2}h1{font-size:34px}.big{font-size:52px}}
  .tickets div{break-inside:avoid;padding:2px 0;border-bottom:1px dashed #1c1c1c}
  .winner{border:2px solid var(--orange);background:#0d0a06}
  .winner .ticket{font-family:monospace;font-size:38px;font-weight:700;color:var(--orange);word-break:break-all}
  .winner .ticket.small{font-size:24px;color:var(--muted)}
  .winner .ticket.struck{font-size:24px;color:var(--muted);text-decoration:line-through;text-decoration-color:var(--orange-2);text-decoration-thickness:3px}
  .winner h2 + .sub{margin-bottom:6px}
  .winner .mine{font-family:monospace;font-size:26px;font-weight:700;color:var(--orange);line-height:1.35}
  .claimed{color:var(--green);font-weight:700}
  .mono{font-family:monospace;font-size:13px;color:#9a9a9a;word-break:break-all}
  .buyrow{display:flex;gap:10px;align-items:stretch}
  .buyrow input{width:110px;margin:0;font-size:22px;font-weight:700;text-align:center}
  .buyrow button{margin:0;flex:1}
  label{display:block;font-size:13px;color:var(--muted);margin-top:14px}
  input,select{width:100%;padding:11px 12px;background:#000;border:1px solid var(--line);color:#fff;
        font-family:monospace;font-size:15px;margin-top:6px}
  input:focus,select:focus{outline:2px solid var(--orange);outline-offset:0}
  .prize{padding:12px 0;border-top:1px dashed #2a2a2a}
  .prize:first-of-type{border-top:0}
  .prize .lbl{font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
  button{margin-top:12px;padding:12px 18px;background:var(--orange);color:#000;border:0;
         font-weight:900;text-transform:uppercase;letter-spacing:.08em;font-size:14px;cursor:pointer}
  button.ghost{background:transparent;color:var(--txt);border:1px solid var(--line)}
  button:hover{background:var(--orange-2)}
  button.ghost:hover{background:#1a1a1a}
  button:focus-visible{outline:2px solid var(--green);outline-offset:2px}
  .result{margin-top:12px;font-family:monospace;font-size:15px;word-break:break-all}
  .ok{color:var(--green)} .bad{color:var(--orange)}
  details{margin-top:18px}
  summary{cursor:pointer;color:var(--muted);font-size:14px}
  footer{max-width:720px;margin:0 auto;padding:0 20px 40px;color:var(--muted);font-size:13px;line-height:1.5}
  footer ol{padding-left:20px;margin:8px 0 0}
  footer li{margin-bottom:6px}
  footer code{font-family:monospace;color:var(--txt)}
  @media (prefers-reduced-motion:no-preference){.pulse{animation:p 2s ease-in-out infinite}}
  @keyframes p{50%{opacity:.4}}
</style>
</head>
"""

PAGE = HEAD + r"""<body>
<header>
  {% if has_logo %}<img class="logo" src="logo" alt="{{ name }}">{% endif %}
</header>

<main>
  <h1>{{ name }}</h1>
  <div class="subtitle">{{ subtitle }}</div>
  <span class="phase" id="phase">loading</span>

  <section class="panel" id="buy-panel" hidden>
    {% if has_prize_image %}<figure class="prize-photo">
      <img src="prize-image" alt="{{ main_prize or 'Main prize' }}">
    </figure>{% endif %}
    {% if prizes|length > 1 or main_prize %}<ul class="prize-list">
      {% for n, label in prizes %}<li>Prize {{ n }}: {{ label or ("Main prize" if n == 1 else "") }}</li>
      {% endfor %}
    </ul>{% endif %}
    <h2>Buy tickets</h2>
    <div class="buyrow">
      <input id="buy-count" type="number" min="1" value="1" inputmode="numeric" aria-label="Number of tickets">
      <button id="buy-btn">Buy tickets</button>
    </div>
    <div class="sub" id="buy-total"></div>
    <div class="result" id="buy-result"></div>
  </section>

  <section class="panel winner" id="my-panel" hidden>
    <h2>Your tickets</h2>
    <div id="my-result" class="result"></div>
  </section>

  <section class="panel">
    <h2>Tickets sold</h2>
    <div class="big" id="count">–</div>
    <div class="sub" id="window"></div>
    <div class="tickets" id="tickets"></div>
    <details id="lookup">
      <summary>Find my ticket number</summary>
      <label>Your ticket ID (the memo on the payment in your wallet, e.g. Kq7zR2x-48213 → Kq7zR2x)
        <input id="lookup-id" autocomplete="off" spellcheck="false" autocapitalize="off" maxlength="13">
      </label>
      <button class="ghost" id="lookup-btn">Look up</button>
      <div class="result" id="lookup-result"></div>
    </details>
  </section>

  <section id="draw"></section>

</main>

<footer>
  <strong>How the draw works — check it yourself with any Bitcoin node.</strong>
  <ol>
    <li>When sales close, the list of all ticket numbers is frozen and sorted in plain byte order
        (digits first, then capital letters, then lower-case letters; case matters).
        Its SHA-256 hash is published here before the drawing block exists, so the list cannot be changed afterwards.</li>
    <li>The drawing block is the first Bitcoin block with a timestamp at or after the closing time.
        Nobody can predict its hash.</li>
    <li>Round n picks one ticket: SHA-256 of the text <code>blockhash,ticket1,ticket2,…,n</code>
        (block hash, then the sorted list, then the round number, all joined with commas) is read as a number
        and divided by the number of tickets still in the pool; the remainder is the position of the winning ticket in the pool.</li>
    <li>The drawn ticket leaves the pool; other tickets of the same buyer stay in. The next round uses the same
        frozen list in the hash, only the pool shrinks.</li>
    <li>The first rounds are the prizes in order. Further rounds draw backup tickets, used only if a winner does not show up.</li>
  </ol>
</footer>

<script>
const $ = id => document.getElementById(id);
const el = (tag, text, cls) => { const e = document.createElement(tag); if (text != null) e.textContent = text; if (cls) e.className = cls; return e; };

async function post(url, body){
  const r = await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  return {ok:r.ok, data: await r.json().catch(()=>({}))};
}

function renderDraw(d){
  const box = $('draw'); box.replaceChildren();
  if (d.phase === 'sales') return;

  if (d.commitment){
    const p = el('section', null, 'panel');
    p.append(el('h2','Sales closed — list frozen'));
    p.append(el('div', `${d.commitment.ticket_count} tickets · SHA-256 of ticket list:`, 'sub'));
    p.append(el('div', d.commitment.sha256_of_ticket_list, 'mono'));
    p.append(el('div', `Rule: ${d.commitment.rule} (${d.commitment.end_time})`, 'sub'));
    box.append(p);
  }
  if (d.phase === 'drawing'){
    const p = el('section', null, 'panel');
    p.append(el('h2','Waiting for the next block'));
    p.append(el('div','Miners are picking the winner…','pulse'));
    box.append(p);
  }
  if (d.phase === 'no_entries'){
    box.append(Object.assign(el('section', null, 'panel'), {textContent:'No paid tickets — no draw.'}));
  }
  if (d.winner){
    const w = d.winner;
    const p = el('section', null, 'panel winner');
    p.append(el('h2', w.prizes.length > 1 ? 'Winning tickets' : 'Winning ticket'));
    for (const pr of w.prizes){
      const row = el('div', null, 'prize');
      if (w.prizes.length > 1) row.append(el('div', pr.label, 'lbl'));
      for (const t of (pr.forfeited || [])) row.append(el('div', t, 'ticket struck'));
      row.append(el('div', pr.ticket, 'ticket'));
      if (pr.from_backup) row.append(el('div', 'Previous winner did not show up — redrawn from the backup list.', 'sub'));
      if (pr.claimed) row.append(el('div','Claimed.','claimed'));
      p.append(row);
    }
    const det = el('details'); det.append(el('summary','Verify the draw'));
    det.append(el('div', `Block ${w.block_height} — ${w.block_hash}`, 'mono'));
    for (const pr of w.prizes){
      det.append(el('div', `Round ${pr.prize} (${pr.label}): index ${pr.index} of ${pr.pool_size} remaining`, 'sub'));
      det.append(el('div', `SHA-256: ${pr.sha256}`, 'mono'));
    }
    p.append(det);
    box.append(p);
  }
}

let PRICE = 0;
function updateTotal(){
  const n = parseInt($('buy-count').value || '0', 10);
  $('buy-total').textContent = n > 0 ? `${n} × ${PRICE} sats = ${n * PRICE} sats` : '';
}
$('buy-count').addEventListener('input', updateTotal);

$('buy-btn').onclick = async () => {
  const count = parseInt($('buy-count').value || '0', 10);
  const r = $('buy-result'); r.textContent = 'Creating invoice…'; r.className = 'result';
  $('buy-btn').disabled = true;
  const {ok, data} = await post('/api/buy', {count});
  $('buy-btn').disabled = false;
  if (!ok){ r.textContent = data.error || 'Error'; r.className = 'result bad'; return; }
  r.textContent = 'Redirecting to checkout…';
  window.location.href = data.checkoutLink;
};

const myInvoice = new URLSearchParams(location.search).get('invoice');
let myPollTimer = null;
async function checkMyTickets(){
  if (!myInvoice) return;
  const panel = $('my-panel'), r = $('my-result'); panel.hidden = false;
  const res = await fetch('/api/my-tickets?invoice=' + encodeURIComponent(myInvoice));
  const d = await res.json().catch(()=>({}));
  if (d.status === 'settled'){
    r.replaceChildren(el('div','Payment confirmed. Your ticket numbers:','ok'),
      ...d.tickets.map(t => el('div', t, 'mine')),
      el('div','Your verification code is the 5 digits after the ticket ID in the memo of this payment in your wallet. Keep it private; if you win, show it at the counter.','sub'));
    clearInterval(myPollTimer);
  } else if (d.error){
    r.textContent = d.error; r.className = 'result bad'; clearInterval(myPollTimer);
  } else {
    r.textContent = `Waiting for payment confirmation (${d.status || 'pending'})…`; r.className = 'result pulse';
  }
}

async function refresh(){
  const d = await (await fetch('/api/status')).json();
  PRICE = d.ticket_price_sats;
  $('buy-panel').hidden = !d.sales_open;
  $('buy-count').max = d.max_per_invoice;
  updateTotal();
  const labels = {sales:'Sales open', drawing:'Drawing', winner:'Winner announced', no_entries:'No entries'};
  const fmt = iso => new Date(iso).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'});
  let label = labels[d.phase] || d.phase;
  if (d.phase === 'sales' && !d.sales_open){
    label = Date.now() < new Date(d.start_time).getTime() ? `Sales open at ${fmt(d.start_time)}` : 'Sales closed';
  }
  const ph = $('phase'); ph.textContent = label;
  ph.className = 'phase ' + (d.sales_open?'live':d.phase==='winner'?'done':'');
  $('count').textContent = d.tickets.length;
  $('window').textContent = `${d.ticket_price_sats} sats per ticket · ${d.start_time} → ${d.end_time}`;
  $('tickets').replaceChildren(...d.tickets.map(t => el('div', t)));
  renderDraw(d);
}

$('lookup-btn').onclick = async () => {
  const {ok, data} = await post('/api/lookup', {ticket_id: $('lookup-id').value});
  const r = $('lookup-result');
  r.textContent = ok ? 'Your tickets: ' + data.tickets.join(', ') : (data.error || 'Not found');
  r.className = 'result ' + (ok ? 'ok' : 'bad');
};
refresh(); setInterval(refresh, 5000);
if (myInvoice){ checkMyTickets(); myPollTimer = setInterval(checkMyTickets, 3000); }
</script>
</body>
</html>"""


if __name__ == "__main__":
    threading.Thread(target=background_loop, daemon=True).start()
    # Dev only. In production run e.g.:
    #   waitress-serve --listen=127.0.0.1:5000 lottery_app_v2:app
    # behind an HTTPS reverse proxy (Caddy/nginx), and start the background
    # thread from a single worker process.
    app.run(host="127.0.0.1", port=5000, debug=False)


ORGANIZER_PAGE = HEAD + r"""<body>
<main>
  <h1>{{ name }}</h1>
  <div class="subtitle">Organizer — claims &amp; backups. Keep this screen away from the audience.</div>
  <span class="phase" id="phase">loading</span>

  <section class="panel">
    <h2>Organizer token</h2>
    <label>Token from .env (ADMIN_TOKEN)
      <input id="v-token" type="password" autocomplete="off">
    </label>
    <div class="result" id="token-result"></div>
  </section>

  <section class="panel winner" id="prizes-panel" hidden>
    <h2>Prizes</h2>
    <div id="prizes"></div>
    <h2>Backup tickets (in order)</h2>
    <div class="sub">Private. Used only if a winner has left before claiming.</div>
    <div id="backups"></div>
  </section>

  <section class="panel" id="claim-panel" hidden>
    <h2>Claim at the counter</h2>
    <p>Winner: open the payment in your wallet and show the <strong>verification code</strong>,
       the 5 digits after your ticket ID in the payment memo (e.g. Kq7zR2x-<strong>48213</strong>).</p>
    <label>Prize being claimed
      <select id="v-prize"></select>
    </label>
    <label>Verification code shown by the winner (or the Lightning preimage)
      <input id="v-preimage" autocomplete="off" spellcheck="false" inputmode="numeric">
    </label>
    <button id="verify-btn">Verify</button>
    <button class="ghost" id="forfeit-btn">Winner left — pass prize to next backup</button>
    <button class="ghost" id="reveal-btn">Reveal stored preimage</button>
    <div class="result" id="v-result"></div>
  </section>
</main>

<script>
const $ = id => document.getElementById(id);
const el = (tag, text, cls) => { const e = document.createElement(tag); if (text != null) e.textContent = text; if (cls) e.className = cls; return e; };
async function post(url, body){
  const r = await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});
  return {ok:r.ok, data: await r.json().catch(()=>({}))};
}
const token = () => $('v-token').value.trim();

function render(d){
  const labels = {sales:'Sales open', drawing:'Drawing', winner:'Winner announced', no_entries:'No entries'};
  const ph = $('phase'); ph.textContent = `${labels[d.phase] || d.phase} · ${d.ticket_count} tickets`;
  ph.className = 'phase ' + (d.phase==='winner'?'done':'');
  const has = d.prizes.length > 0;
  $('prizes-panel').hidden = !has; $('claim-panel').hidden = !has;
  if (!has) return;
  const pz = $('prizes'); pz.replaceChildren();
  for (const pr of d.prizes){
    const row = el('div', null, 'prize');
    row.append(el('div', pr.label, 'lbl'));
    for (const t of (pr.forfeited || [])) row.append(el('div', t, 'ticket struck'));
    row.append(el('div', pr.ticket, 'ticket'));
    if (pr.from_backup) row.append(el('div', `From backup ${pr.from_backup}.`, 'sub'));
    if (pr.claimed) row.append(el('div','Claimed — verification code checked.','claimed'));
    pz.append(row);
  }
  const bk = $('backups'); bk.replaceChildren();
  for (const b of d.backups){
    const row = el('div', null, 'prize');
    row.append(el('div', b.label, 'lbl'));
    row.append(el('div', b.ticket, b.used_for ? 'ticket struck' : 'ticket small'));
    if (b.used_for) row.append(el('div', `Took over prize ${b.used_for}.`, 'claimed'));
    bk.append(row);
  }
  if (!d.backups.length) bk.append(el('div','None configured (BACKUP_COUNT=0).','sub'));
  const sel = $('v-prize');
  const wanted = d.prizes.map(pr => `${pr.label} — ${pr.ticket}`).join('|');
  if (sel.dataset.state !== wanted){
    const cur = sel.value;
    sel.replaceChildren(...d.prizes.map(pr => Object.assign(el('option', `${pr.label} — ${pr.ticket}`), {value: pr.prize})));
    if (cur) sel.value = cur;
    sel.dataset.state = wanted;
  }
}

async function refresh(){
  if (!token()) return;
  const {ok, data} = await post('/api/admin/state', {token: token()});
  const tr = $('token-result');
  if (!ok){ tr.textContent = data.error || 'Error'; tr.className = 'result bad'; $('prizes-panel').hidden = $('claim-panel').hidden = true; return; }
  tr.textContent = 'Token accepted.'; tr.className = 'result ok';
  render(data);
}
$('v-token').addEventListener('change', refresh);
$('v-token').addEventListener('keyup', e => { if (e.key === 'Enter') refresh(); });

$('verify-btn').onclick = async () => {
  const {ok, data} = await post('/api/verify', {token: token(), code: $('v-preimage').value, prize: $('v-prize').value});
  const r = $('v-result');
  if (!ok){ r.textContent = data.error || 'Error'; r.className='result bad'; return; }
  r.textContent = data.match ? 'MATCH — hand over the prize.' : 'NO MATCH — wrong code.';
  r.className = 'result ' + (data.match ? 'ok' : 'bad');
  if (data.match) refresh();
};
$('forfeit-btn').onclick = async () => {
  const {ok, data} = await post('/api/forfeit', {token: token(), prize: $('v-prize').value});
  const r = $('v-result');
  r.textContent = ok ? `Prize ${data.prize} now goes to ticket ${data.ticket} (backup ${data.from_backup}).` : (data.error || 'Error');
  r.className = 'result ' + (ok ? 'ok' : 'bad');
  if (ok) refresh();
};
$('reveal-btn').onclick = async () => {
  const {ok, data} = await post('/api/reveal', {token: token(), prize: $('v-prize').value});
  const r = $('v-result');
  r.textContent = ok ? 'Stored preimage: ' + data.preimage : (data.error || 'Error');
  r.className = 'result ' + (ok ? '' : 'bad');
};

setInterval(refresh, 5000);
</script>
</body>
</html>"""
